### PR TITLE
Preserve cabal update post restore

### PR DESCRIPTION
**Pull request by newhoggy**

### CODE REVIEW

**Comment by AlexeyRaga** [comment]
I am hesitant about that because `root.json` is not preserved, and also none of the initial content of the `.cabal` folder, which may be important (or not)

**Comment by newhoggy** [comment]
What about this version?

**Comment by AlexeyRaga** [comment]
There is also `~/.cabal/config`...

**Comment by AlexeyRaga** [comment]
because we start with no `.cabal` in the container, what we can do is:
- do `cabal new-update`
- copy the whole `~/.cabal` folder to `cabal-update`
- restore the cache
- copy all the content of `cabal-update` recursively into `~/.cabal`

**Pull request closed without merging**
